#!/usr/bin/env python3
"""Download and prepare the OpenPVSG dataset.

OpenPVSG project page: https://jingkang50.github.io/OpenPVSG/
GitHub: https://github.com/Jingkang50/OpenPSG

This script documents the expected dataset structure and creates the
required directory layout. Actual data must be downloaded manually
from the project's official sources.

Usage:
    uv run python scripts/download_openpvsg.py --output data/openpvsg
"""

import argparse
import os
import json
from pathlib import Path


EXPECTED_STRUCTURE = """
Expected directory structure after setup:

data/openpvsg/
├── annotations/
│   ├── pvsg.json           # Main annotation file from OpenPVSG
│   ├── train.json          # Train split (generated by prepare script)
│   └── val.json            # Val split (generated by prepare script)
├── videos/                 # Raw video files
│   └── {video_id}.mp4
├── frames/                 # Extracted frames (if using frame-based loading)
│   └── {video_id}/
│       ├── 000000.jpg
│       └── ...
├── masks/                  # Panoptic segmentation masks
│   └── {video_id}/
│       ├── 000000.png
│       └── ...
└── precomputed_features/   # Precomputed tube features (recommended)
    └── {video_id}.pt       # Each file contains:
                            #   entity_labels: [N] tensor
                            #   tube_features: [N, T, D] tensor
                            #   relations: list of dicts
                            #   num_frames: int
"""


def main():
    parser = argparse.ArgumentParser(description="Prepare OpenPVSG dataset")
    parser.add_argument("--output", type=str, default="data/openpvsg")
    args = parser.parse_args()

    root = Path(args.output)

    # Create directories
    for subdir in ["annotations", "videos", "frames", "masks", "precomputed_features"]:
        (root / subdir).mkdir(parents=True, exist_ok=True)

    print("OpenPVSG Dataset Preparation")
    print("=" * 50)
    print(EXPECTED_STRUCTURE)
    print("Steps to complete setup:")
    print("1. Clone OpenPVSG repo: git clone https://github.com/Jingkang50/OpenPSG")
    print("2. Download pvsg.json annotations and place in annotations/")
    print("3. Download videos from ViDOR, Epic-Kitchens, Ego4D")
    print("4. Extract frames if using frame-based loading")
    print("5. Run segmentation model and save precomputed features")
    print("6. Run scripts/prepare_openpvsg.py to generate train/val splits")
    print()
    print(f"Directory structure created at: {root}")


if __name__ == "__main__":
    main()
